# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca1821a9422c8464b5e56cc218b9b64ce1e9c7ad6f37e534c9a8eeab8ff00ba0adc91a05f6b2dd0d564208eb9864c5569a0f2d8aaf8641ec8a20640fd9de22db

test:
  secret_key_base: 018c62c58b5be5954641f1fed581953db765a2108ebb632c10d7a7955c3542477864d78ae389f63d28bd8b0c00354329ee9dd35e441a8a9090ad2a3e5062d721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
